---
- hosts: login
  become: yes
  tags: 
    - base
  roles:
    - packages
    - nextflow
    - libstatgen
    - vep
    - vep_cache
    - ref_data
    - loftee
    - basis_data
    - test_data

- hosts: login
  become: yes
  tags:
    - tooling
  tasks:
    - name: Clone Bravo Data Prep to build tools
      ansible.builtin.git:
        depth: 1
        dest: "/apps/data_prep"
        repo: "https://github.com/statgen/bravo_data_prep.git"

- hosts: login
  tags:
    - pipeline
  tasks:
    - name: Clone Bravo Data Prep for nextflow pipeline
      ansible.builtin.git:
        depth: 1
        dest: "~/data_prep"
        repo: "https://github.com/statgen/bravo_data_prep.git"
