---
- hosts: login
  tags:
    - hack
  tasks:
    - name: Assign ansible user id as owner of /apps
      become: yes
      ansible.builtin.file:
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        path: "/apps"
        state: directory

- hosts: login
  become: yes
  tags: 
    - base
  roles:
    - packages
    - nextflow
    - test_data

- hosts: login
  vars:
    modulepath: "/apps/modulefiles"
  tags:
    - lmod
  tasks:
    - name: Create LMOD modulefiles directory
      ansible.builtin.file:
        owner: "{{ ansible_user_id }}"
        path: "{{modulepath}}"
        state: directory
        mode: 0775

- hosts: login
  tags: 
    - tooling
  vars:
    htslib_dir: "/apps/htslib"
    htslib_ver: "1.15.1"
  roles:
    - libstatgen
    - htslib
    - vep
    - vep_cache
    - loftee
    - samtools
    - basis_data
    - ref_data

- hosts: login
  tags:
    - dprep
  vars:
    - dprep_dir: "/apps/data_prep" 
    - dprep_module: "/apps/modulefiles/data_prep"
  tasks:
    - name: Create data prep tools dir
      ansible.builtin.file:
        owner: "{{ ansible_user_id }}"
        path: "{{ dprep_dir }}"
        state: directory

    - name: Clone Bravo Data Prep to build tools
      ansible.builtin.git:
        depth: 1
        dest: "{{dprep_dir}}"
        repo: "https://github.com/statgen/bravo_data_prep.git"
        version: fr10-prep

    - name: Install cget dependency retrieval tool
      ansible.builtin.pip:
        name: cget
        state: present

    - name: Build cpp tooling
      ansible.builtin.command:
        chdir: "{{dprep_dir}}/tools/cpp_tools"
        argv:
          - "~/.local/bin/cget"
          - "install"
          - "."

    - name: Create cpp tooling LMOD module directory
      ansible.builtin.file:
        owner: "{{ ansible_user_id }}"
        path: "{{ dprep_module }}"
        state: directory

    - name: Create cpp tooling LMOD module file
      ansible.builtin.template:
        dest: "{{ dprep_module }}/0.2.0.lua"
        src: "templates/lmod_data_prep.lua.j2"

- hosts: login
  tags:
    - pipeline
    - exp
  tasks:
    - name: Clone Bravo Data Prep for nextflow pipeline
      ansible.builtin.git:
        depth: 1
        dest: "~/data_prep"
        repo: "https://github.com/statgen/bravo_data_prep.git"
        version: fr10-prep
    - name: Convenience data dir for Coverage workflow
      ansible.builtin.file:
        path: "~/data_prep/workflows/coverage/data"
        state: directory
    - name: Convenience symlinks to reference Coverage workflow
      ansible.builtin.file:
        src: "/apps/reference"
        dest: "~/data_prep/workflows/coverage/data/ref"
        state: link
    - name: Convenience symlinks to crams for Coverage workflow
      ansible.builtin.file:
        src: "/home/test_data/50_sample_input/crams"
        dest: "~/data_prep/workflows/coverage/data/crams"
        state: link

- hosts: login
  vars:
    smoke_test_dir: "~/nf_smoke_test"
  tasks:
    - name: Create Nextflow smoke test dir
      ansible.builtin.file:
        path: "~/nf_smoke_test"
        state: directory
        mode: 0775

    - name: Copy Nextflow smoke test template
      ansible.builtin.template:
        dest: "{{smoke_test_dir}}/main.nf"
        src: "templates/nf_smoke_test.nf.j2"

    - name: Copy Nextflow smoke test config
      ansible.builtin.template:
        dest: "{{smoke_test_dir}}/nextflow.config"
        src: "templates/nextflow.config.j2"
