---
- hosts: login
  tags:
    - hack
  tasks:
    - name: Assign ansible user id as owner of /apps
      become: yes
      ansible.builtin.file:
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        path: "/apps"
        state: directory

- hosts: login
  become: yes
  tags: 
    - base
  roles:
    - packages
    - nextflow

- hosts: login
  gather_facts: no
  vars:
    modulepath: "/apps/modulefiles"
  tags:
    - lmod
  tasks:
    - name: Create LMOD modulefiles directory
      ansible.builtin.file:
        owner: "{{ ansible_user_id }}"
        path: "{{modulepath}}"
        state: directory
        mode: 0775

- hosts: login
  gather_facts: no
  tags: 
    - tooling
  vars:
    htslib_dir: "/apps/htslib"
    htslib_ver: "1.15.1"
  roles:
    - libstatgen
    - htslib
    - vep
    - vep_cache
    - loftee
    - samtools

- hosts: login
  tags: 
    - data
  roles:
    - basis_data
    - ref_data
    - test_data

- hosts: login
  gather_facts: no
  tags:
    - dprep
  vars:
    dprep_dir: "/apps/data_prep" 
    dprep_module: "/apps/modulefiles/data_prep"
  tasks:
    - name: Create data prep tools dir
      ansible.builtin.file:
        owner: "{{ ansible_user_id }}"
        path: "{{ dprep_dir }}"
        state: directory

    - name: Clone Bravo Data Prep to build tools
      ansible.builtin.git:
        depth: 1
        dest: "{{dprep_dir}}"
        repo: "https://github.com/statgen/bravo_data_prep.git"
        version: fr10-prep

    - name: Install cget dependency retrieval tool
      ansible.builtin.pip:
        name: cget
        state: present

    - name: Build cpp tooling
      ansible.builtin.command:
        chdir: "{{dprep_dir}}/tools/cpp_tools"
        argv:
          - "~/.local/bin/cget"
          - "install"
          - "."

    - name: Create cpp tooling LMOD module directory
      ansible.builtin.file:
        owner: "{{ ansible_user_id }}"
        path: "{{ dprep_module }}"
        state: directory

    - name: Create cpp tooling LMOD module file
      ansible.builtin.template:
        dest: "{{ dprep_module }}/0.2.0.lua"
        src: "templates/lmod_data_prep.lua.j2"

- hosts: login
  gather_facts: no
  tags:
    - pipeline
  vars:
    loftee_dir: "/apps/loftee"
    loftee_data: "/apps/loftee_data"
  tasks:
    - name: Clone Bravo Data Prep for nextflow pipeline
      ansible.builtin.git:
        depth: 1
        dest: "~/data_prep"
        repo: "https://github.com/statgen/bravo_data_prep.git"
        version: fr10-prep

    - name: Convenience data dir for Coverage workflow
      ansible.builtin.file:
        path: "~/data_prep/workflows/coverage/data"
        state: directory
      loop:

    - name: Convenience symlinks Coverage workflow
      ansible.builtin.file:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        state: link
      loop:
        - src: "/apps/reference"
          dest: "~/data_prep/workflows/coverage/data/ref"

        - src: "/home/test_data/50_sample_input/crams"
          dest: "~/data_prep/workflows/coverage/data/crams"

    - name: Convenience symlinks for Prepare VCF workflow
      ansible.builtin.file:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        state: link
      loop:
        - src: "/apps/loftee"
          dest: "~/data_prep/workflows/prepare_vcf/loftee"

        - src: "/apps/loftee_data"
          dest: "~/data_prep/workflows/prepare_vcf/loftee_data"

        - src: "/apps/data_prep/tools/py_tools/add_cadd_scores.py"
          dest: "~/data_prep/workflows/prepare_vcf/add_cadd_scores.py"

        - src: "/home/test_data/50_sample_input/bcfs"
          dest: "~/data_prep/workflows/prepare_vcf/bcfs"

- hosts: login
  gather_facts: no
  vars:
    smoke_test_dir: "~/nf_smoke_test"
  tasks:
    - name: Create Nextflow smoke test dir
      ansible.builtin.file:
        path: "~/nf_smoke_test"
        state: directory
        mode: 0775

    - name: Copy Nextflow smoke test template
      ansible.builtin.template:
        dest: "{{smoke_test_dir}}/main.nf"
        src: "templates/nf_smoke_test.nf.j2"

    - name: Copy Nextflow smoke test config
      ansible.builtin.template:
        dest: "{{smoke_test_dir}}/nextflow.config"
        src: "templates/nextflow.config.j2"

- hosts: login
  gather_facts: no
  vars:
    python_lib: "/apps/python3/lib"
    python_module: "/apps/modulefiles/python3"
  tasks:
    - name: Create Python3 shared libraries dir
      ansible.builtin.file:
        path: "{{item}}"
        state: directory
        mode: 0775
      loop:
        - "{{python_lib}}"
        - "{{python_lib}}/bin"

    - name: Hack symlink python3 to preempt python2 in PATH 
      ansible.builtin.file:
        src: "/usr/bin/python3"
        path: "{{python_lib}}/bin/python"
        state: link

    - name: Install shared python libraries
      ansible.builtin.pip:
        name: "{{item}}"
        extra_args: "--target {{python_lib}}"
      loop:
        - pysam
        - numpy
        - python-rapidjson

    - name: Create python alias LMOD module directory
      ansible.builtin.file:
        owner: "{{ ansible_user_id }}"
        path: "{{ python_module }}"
        state: directory

    - name: Create python alias LMOD module file
      ansible.builtin.template:
        dest: "{{ python_module }}/python_alias.lua"
        src: "templates/lmod_python3.lua.j2"
