---
- hosts: login
  tags:
    - hack
  tasks:
    - name: Assign ansible user id as owner of /apps
      become: yes
      ansible.builtin.file:
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        path: "/apps"
        state: directory

- hosts: login
  become: yes
  tags: 
    - base
  roles:
    - packages
    - nextflow

- hosts: login
  gather_facts: yes
  vars:
    modulepath: "/apps/modulefiles"
  tags:
    - lmod
  tasks:
    - name: Create LMOD modulefiles directory
      become: yes
      ansible.builtin.file:
        owner: "{{ ansible_user_id }}"
        path: "{{modulepath}}"
        state: directory
        mode: 0775
    - name: Configure LMOD to use module directory
      become: yes
      ansible.builtin.copy:
        dest: "/etc/profile.d/lmod_modulepath.sh"
        content: "export MODULEPATH=/apps/modulefiles"
        mode: 0755

- hosts: login
  gather_facts: yes
  tags: 
    - tooling
  vars:
    htslib_dir: "/apps/htslib"
    htslib_ver: "1.15.1"
  roles:
    - libstatgen
    - htslib
    - vep
    - vep_cache
    - loftee
    - samtools
    - mlr
    - mosdepth
    - bcftools
    - python3
    - data_prep_tooling

- hosts: login
  tags: 
    - data
  roles:
    - basis_data
    - ref_data
    - role: test_data
      become: yes

- hosts: login
  gather_facts: no
  tags:
    - pipeline
  roles:
    - pipeline
