---
- hosts: login
  become: yes
  tags: 
    - base
  roles:
    - packages
    - nextflow
    - libstatgen
    - vep
    - vep_cache
    - ref_data
    - loftee
    - basis_data
    - test_data
    - samtools

- hosts: login
  vars:
    modulepath: "/apps/modulefiles"
  tags:
    - lmod
  tasks:
    - name: Create LMOD modulefiles directory
      become: yes
      ansible.builtin.file:
        owner: "{{ ansible_user_id }}"
        path: "{{modulepath}}"
        state: directory
        mode: 0775

- hosts: login
  tags:
    - tooling
  vars:
    - dprep_dir: "/apps/data_prep" 
  tasks:
    - name: Create data prep tools dir
      become: yes
      ansible.builtin.file:
        owner: "{{ ansible_user_id }}"
        path: "{{ dprep_dir }}"
        state: directory
        recurse: yes

    - name: Clone Bravo Data Prep to build tools
      ansible.builtin.git:
        depth: 1
        dest: "{{dprep_dir}}"
        repo: "https://github.com/statgen/bravo_data_prep.git"
        version: fr10-prep

    - name: Install cget dependency retrieval tool
      ansible.builtin.pip:
        name: cget
        state: present

    - name: Build cpp tooling
      ansible.builtin.command:
        chdir: "{{dprep_dir}}/tools/cpp_tools"
        argv:
          - "~/.local/bin/cget"
          - "install"
          - "."

- hosts: login
  tags:
    - pipeline
  tasks:
    - name: Clone Bravo Data Prep for nextflow pipeline
      ansible.builtin.git:
        depth: 1
        dest: "~/data_prep"
        repo: "https://github.com/statgen/bravo_data_prep.git"
        version: fr10-prep

- hosts: login
  vars:
    smoke_test_dir: "~/nf_smoke_test"
  tasks:
    - name: Create Nextflow smoke test dir
      ansible.builtin.file:
        path: "~/nf_smoke_test"
        state: directory
        mode: 0775

    - name: Copy Nextflow smoke test template
      ansible.builtin.template:
        dest: "{{smoke_test_dir}}/main.nf"
        src: "templates/nf_smoke_test.nf.j2"

    - name: Copy Nextflow smoke test config
      ansible.builtin.template:
        dest: "{{smoke_test_dir}}/nextflow.config"
        src: "templates/nextflow.config.j2"
