---
- name: Install dependencies for pipeline tooling
  ansible.builtin.apt:
    pkg:
      - jq
      - openjdk-11-jre-headless
      - git
      - cmake
      - zlib1g-dev
      - libbz2-dev
      - liblzma-dev
      - cpanminus
      - openssl
      - libminizip1
      - minizip
      - unzip
      - libpng-dev
      - libssl-dev
      - libmariadbclient-dev
      - libmariadbclient-dev-compat

    state: present
    update_cache: yes
