---
- name: Clone Bravo Data Prep for nextflow pipeline
  ansible.builtin.git:
    depth: 1
    dest: "{{dprep_dir}}"
    repo: "https://github.com/statgen/bravo_data_prep.git"
    version: main

- name: Convenience data and crams dir for Coverage workflow
  ansible.builtin.file:
    path: "{{dprep_dir}}/workflows/coverage/data/crams"
    state: directory

- name: Convenience symlinks Coverage workflow
  ansible.builtin.file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    state: link
  loop:
    - src: "/apps/reference"
      dest: "{{dprep_dir}}/workflows/coverage/data/ref"

- name: Convenience data dir for process vcf workflow
  ansible.builtin.file:
    path: "{{proc_vcf_dir}}/data/bcfs"
    state: directory

- name: Convenience symlinks for process vcf workflow
  ansible.builtin.file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    state: link
  loop:
    - src: "/apps/data_prep/tools/py_tools/add_cadd_scores.py"
      dest: "{{proc_vcf_dir}}/add_cadd_scores.py"

    - src: "/mnt/vcfs/freeze10/subsets/topmed/sites"
      dest: "{{proc_vcf_dir}}/data/bcfs/sites" 

    - src: "/mnt/vcfs/freeze10/genotypes/merged"
      dest: "{{proc_vcf_dir}}/data/bcfs/full" 

- name: Convenience data dir for sequences workflow
  ansible.builtin.file:
    path: "~/data_prep/workflows/sequences/data"
    state: directory

- name: Convenience symlinks for sequences workflow
  ansible.builtin.file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    state: link
  loop:
    - src: "/home/test_data/50_sample_input/bcfs"
      dest: "~/data_prep/workflows/sequences/data/bcfs"

    - src: "/home/test_data/50_sample_input/crams"
      dest: "~/data_prep/workflows/sequences/data/crams"

    - src: "/apps/reference"
      dest: "~/data_prep/workflows/sequences/data/ref"

- name: Create Nextflow smoke test dir
  ansible.builtin.file:
    path: "~/nf_smoke_test"
    state: directory
    mode: 0775

- name: Copy Nextflow smoke test template
  ansible.builtin.template:
    dest: "{{smoke_test_dir}}/main.nf"
    src: "templates/nf_smoke_test.nf.j2"

- name: Copy Nextflow smoke test config
  ansible.builtin.template:
    dest: "{{smoke_test_dir}}/nextflow.config"
    src: "templates/nextflow.config.j2"
