---
- name: Create mosdepth directory
  ansible.builtin.file:
    path: "{{ version_dir }}"
    state: directory
    mode: 0775

- name: Download mosdepth binary to version directory
  ansible.builtin.get_url:
    url: "{{ download_url }}"
    dest: "{{ version_dir }}"
    mode: 0775

- name: Create mosdepth module directory
  ansible.builtin.file:
    path: "/apps/modulefiles/mosdepth"
    state: directory
    mode: 0775

- name: Create mosdepth LMOD module file
  ansible.builtin.template:
    dest: "/apps/modulefiles/mosdepth/{{mosdepth_version}}.lua"
    src: "templates/lmod_module.lua.j2"
