---
- name: Create nextflow install dir
  ansible.builtin.file:
    path: "{{nf_install_dir}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Download nextflow
  ansible.builtin.uri:
    url: "{{ nf_releases }}/v{{ nf_version }}/nextflow"
    dest: "{{ nf_install_dir }}/nextflow"
    creates: "{{ nf_install_dir }}/nextflow"

- name: Mark Nextflow as executable
  ansible.builtin.file:
    dest: "{{ nf_install_dir }}/nextflow"
    mode: 0755
    owner: root

- name: Add nextflow to PATH
  ansible.builtin.copy:
    dest: "/etc/profile.d/nextflow.sh"
    content: "PATH=\"${PATH}:{{nf_install_dir}}\""
    mode: 0644
    owner: root
