---
- name: Create Python3 shared libraries dir
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    mode: 0775
  loop:
    - "{{python_lib}}"
    - "{{python_lib}}/bin"

- name: Hack symlink python3 to preempt python2 in PATH 
  ansible.builtin.file:
    src: "/usr/bin/python3"
    path: "{{python_lib}}/bin/python"
    state: link

- name: Install shared python libraries
  ansible.builtin.pip:
    name: "{{item}}"
    extra_args: "--target {{python_lib}}"
  loop:
    - pysam
    - numpy
    - python-rapidjson

- name: Create python alias LMOD module directory
  ansible.builtin.file:
    path: "{{ python_module }}"
    state: directory

- name: Create python alias LMOD module file
  ansible.builtin.template:
    dest: "{{ python_module }}/python_alias.lua"
    src: "templates/lmod_module.lua.j2"
