---
- name: Clone Loftee Plugin
  ansible.builtin.git:
    repo: "https://github.com/konradjk/loftee.git"
    depth: 1
    dest: "{{loftee_dir}}"
    single_branch: yes
    version: grch38

- name: Create lofte data dir
  ansible.builtin.file:
    path: "{{loftee_data}}"
    state: directory
    mode: 0755

- name: Retrieve human ancestor reference
  block:
    - name: Copy human ancestor files from cache bucket
      ansible.builtin.command:
        argv:
          - "gsutil"
          - "cp"
          - "gs://{{cache_bucket}}/{{item}}"
          - "{{loftee_data}}/{{item}}"
        creates: "{{loftee_data}}/{{item}}"
      loop:
        - human_ancestor.fa.gz
        - human_ancestor.fa.gz.fai
        - human_ancestor.fa.gz.gzi
  rescue:
    - name: Copy human ancestor reference
      ansible.builtin.get_url:
        url: "{{item}}"
        dest: "{{loftee_data}}/{{item | basename}}"
        mode: 0755
      loop:
        - https://s3.amazonaws.com/bcbio_nextgen/human_ancestor.fa.gz
        - https://s3.amazonaws.com/bcbio_nextgen/human_ancestor.fa.gz.fai
        - https://s3.amazonaws.com/bcbio_nextgen/human_ancestor.fa.gz.gzi

- name: Retrieve GERP scores for GRCh38
  block:
    - name: Copy GERP scores from cache bucket
      ansible.builtin.command:
        argv:
          - "gsutil"
          - "cp"
          - "gs://{{cache_bucket}}/gerp_conservation_scores.homo_sapiens.GRCh38.bw"
          - "{{loftee_data}}/gerp_conservation_scores.homo_sapiens.GRCh38.bw"
        creates: "{{loftee_data}}/gerp_conservation_scores.homo_sapiens.GRCh38.bw"
  rescue:
    - name: Copy GERP scores from Ensembl
      ansible.builtin.get_url:
        url: "{{ gerp_scores_url }}"
        dest: "{{loftee_data}}/gerp_conservation_scores.homo_sapiens.GRCh38.bw"
        mode: 0644

- name: Retrieve loftee conservation sql lookup for hg38
  block:
    - name: Copy GERP scores from cache bucket
      ansible.builtin.command:
        argv:
          - "gsutil"
          - "cp"
          - "gs://{{cache_bucket}}/loftee.sql.gz"
          - "{{loftee_data}}/loftee.sql.gz"
        creates: "{{loftee_data}}/loftee.sql.gz"
  rescue:
    - name: Copy conservation sql from konradk at Broad
      ansible.builtin.get_url:
        url: https://personal.broadinstitute.org/konradk/loftee_data/GRCh38/loftee.sql.gz 
        dest: "{{loftee_data}}/loftee.sql.gz"
        mode: 0644
