---
- name: Create shared for Perl dependencies.
  ansible.builtin.file:
    path: "{{perl5modules_basedir}}"
    state: directory
    mode: 0755

- name: Install VEP Perl dependencies.
  community.general.cpanm:
    pkg: "{{item}}" 
    locallib: "{{perl5modules_basedir}}"
  environment:
    HTSLIB_DIR: "{{htslib_dir}}/htslib-{{htslib_ver}}"
  loop:
    - Module::Build
    - Bio::Root::Version
    - Try::Tiny
    - Bio::DB::HTS::Tabix
    - Set::IntervalTree
    - JSON
    - PerlIO::gzip
    - Test::Warnings

- name: Clone VEP
  ansible.builtin.git:
    repo: "https://github.com/Ensembl/ensembl-vep.git"
    depth: 1
    version: release/105.0
    dest: "{{vep_dir}}"

- name: Check if VEP already installed via ansible
  ansible.builtin.stat:
    get_attributes: no
    get_checksum: no
    get_mime: no
    path: "{{vep_dir}}/.ansible_lock"
  register: vep_install_lock

- name: Install VEP
  ansible.builtin.command:
    chdir: "{{vep_dir}}"
    cmd: "perl INSTALL.pl --CACHEDIR {{vep_cache_dir}} --PLUGINS all --AUTO ap -q -n"
  register: vep_install
  environment:
    PERL5LIB: "{{perl5lib}}"
  when: vep_install_lock.stat.exists == false

- name: Create VEP install lockfile
  ansible.builtin.copy:
    dest: "{{vep_dir}}/.ansible_lock"
    content: "VEP installed via Ansible"
  when: vep_install.changed

- name: Create VEP module directory
  ansible.builtin.file:
    path: "/apps/modulefiles/vep"
    state: directory
    mode: 0775

- name: Create VEP LMOD module file
  ansible.builtin.template:
    dest: "/apps/modulefiles/vep/105.0.lua"
    src: "templates/lmod_module.lua.j2"
