---
samtools_version: "1.15.1"
base_url: "https://github.com/samtools/samtools/releases/download"
download_url: "{{base_url}}/{{samtools_version}}/samtools-{{samtools_version}}.tar.bz2" 
base_dir: "/apps/samtools"
version_dir: "{{base_dir}}/samtools-{{samtools_version}}"
