---
- name: Make api backing data directory
  ansible.builtin.file:
    path: "{{api_dir}}"
    state: directory

- name: Get canonical transcripts
  ansible.builtin.uri:
    url: "{{biomart_url}}?query={{transcripts_xml | urlencode}}"
    dest:    "{{api_dir}}/canonical_transcripts.tsv"
    creates: "{{api_dir}}/canonical_transcripts.tsv"

- name: Gzip canonical transcripts
  community.general.archive:
    path: "{{api_dir}}/canonical_transcripts.tsv"
    dest: "{{api_dir}}/canonical_transcripts.tsv.gz"

- name: Get OMIM file
  ansible.builtin.uri:
    url: "{{biomart_url}}?query={{omim_xml | urlencode}}"
    dest:    "{{api_dir}}/omim_ensembl_refs.tsv"
    creates: "{{api_dir}}/omim_ensembl_refs.tsv"

- name: Gzip OMIM file
  community.general.archive:
    path: "{{api_dir}}/omim_ensembl_refs.tsv"
    dest: "{{api_dir}}/omim_ensembl_refs.tsv.gz"

- name: Get genecode annotations
  ansible.builtin.uri:
    url: "{{genecode_url}}"
    dest:    "{{api_dir}}/gencode.v38.annotation.gtf.gz"
    creates: "{{api_dir}}/gencode.v38.annotation.gtf.gz"

- name: Get HUGO custom results
  ansible.builtin.uri:
    url: "https://www.genenames.org/cgi-bin/download/custom?\
      col=gd_app_sym&col=gd_app_name&col=gd_prev_sym&col=gd_aliases&\
      col=gd_pub_ensembl_id&status=Approved&order_by=gd_app_sym_sort&\
      format=text&submit=submit"
    dest:    "{{api_dir}}/hgcn_custom_results.tsv"
    creates: "{{api_dir}}/hgcn_custom_results.tsv"

- name: Copy HUGO custom header
  ansible.builtin.copy:
    src: "files/hgcn_header.tsv"
    dest: "{{api_dir}}/hgcn_genenames.tsv"
    force: no

- name: Append HUGO data under custom header
  ansible.builtin.shell:
    chdir: "{{api_dir}}"
    cmd: tail -n +2 hgcn_custom_results.tsv >> hgcn_genenames.tsv
    creates: "{{api_dir}}/hgcn_genenames.tsv.gz"

- name: Gzip HUGO gene names
  community.general.archive:
    path: "{{api_dir}}/hgcn_genenames.tsv"
    dest: "{{api_dir}}/hgcn_genenames.tsv.gz"
