---
- name: Create references directories
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    mode: 0755
  loop:
    - "{{refs_dir}}"
    - "{{refs_dir}}/cadd"

- name: Ref sub tasks
  include_tasks: "{{task_item}}"
  loop:
    - hs_fasta.yml
    - cadd.yml
    - bravo_refs.yml
  loop_control:
    loop_var: task_item
