---
- name: Create references directories
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    mode: 0755
  loop:
    - "{{refs_dir}}"
    - "{{refs_dir}}/cadd"

- name: Copy fasta and fasta index
  block:
    - name: Copy homosapiens fasta from cache bucket
      ansible.builtin.command:
        chdir: "{{refs_dir}}"
        argv:
          - "gsutil"
          - "cp"
          - "gs://{{cache_bucket}}/hs38DH.fa"
          - "{{refs_dir}}/hs38DH.fa"
        creates: "{{refs_dir}}/hs38DH.fa"

    - name: Copy homosapiens fasta index from cache bucket
      ansible.builtin.command:
        chdir: "{{refs_dir}}"
        argv:
          - "gsutil"
          - "cp"
          - "gs://{{cache_bucket}}/hs38DH.fa.fai"
          - "{{refs_dir}}/hs38DH.fa.fai"
        creates: "{{refs_dir}}/hs38DH.fa.fai"

  rescue:
    - name: Copy homosapiens fasta from sph.umich.edu
      ansible.builtin.get_url:
        url: ftp://anonymous@share.sph.umich.edu/bravo/ref/hs38DH.fa 
        dest: "{{refs_dir}}/hs38DH.fa"
        mode: 0644

    - name: Copy homosapiens fasta index from sph.umich.edu
      ansible.builtin.get_url:
        url: ftp://anonymous@share.sph.umich.edu/bravo/ref/hs38DH.fa.fai 
        dest: "{{refs_dir}}/hs38DH.fa.fai"
        mode: 0644

- name: Download CADD scores
  block:
    - name: Obtain CADD scores from cache bucket
      ansible.builtin.command:
        chdir: "{{refs_dir}}/cadd"
        argv:
          - "gsutil"
          - "cp"
          - "gs://{{cache_bucket}}/{{item}}"
          - "{{item}}"
        creates: "{{refs_dir}}/cadd/{{item}}"
      loop:
        - whole_genome_SNVs.tsv.gz
        - whole_genome_SNVs.tsv.gz.tbi

  rescue:
    - name: Obtain whole genome cadd from washington.edu
      ansible.builtin.get_url:
        url: https://krishna.gs.washington.edu/download/CADD/v1.6/GRCh38/whole_genome_SNVs.tsv.gz
        dest: "{{refs_dir}}/cadd/whole_genome_SNVs.tsv.gz"
        mode: 0644

    - name: Obtain whole genome cadd index from washington.edu
      ansible.builtin.get_url:
        url: https://krishna.gs.washington.edu/download/CADD/v1.6/GRCh38/whole_genome_SNVs.tsv.gz.tbi 
        dest: "{{refs_dir}}/cadd/hs38DH.fa.fai"
        mode: 0644

