---
- name: Create miller base directory
  ansible.builtin.file:
    path: "{{ base_dir }}"
    state: directory
    mode: 0775

- name: Unpack miller into version directory
  ansible.builtin.unarchive:
    remote_src: yes
    src: "{{download_url}}"
    dest: "{{ base_dir }}"
    creates: "{{ version_dir }}"

- name: Create miller module directory
  ansible.builtin.file:
    path: "/apps/modulefiles/miller"
    state: directory
    mode: 0775

- name: Create miller LMOD module file
  ansible.builtin.template:
    dest: "/apps/modulefiles/miller/{{miller_version}}.lua"
    src: "templates/lmod_module.lua.j2"
