---
- name: Clone lib StatGen dependency 
  ansible.builtin.git:
    depth: 1
    dest: "{{libstatgen_dir}}"
    repo: "https://github.com/statgen/libStatGen.git"

- name: Build lib StatGen dependency 
  community.general.make:
    chdir: "{{libstatgen_dir}}"

- name: Clone StatGen bamUtil 
  ansible.builtin.git:
    depth: 1
    dest: "{{bamutil_dir}}"
    repo: "https://github.com/statgen/bamUtil.git"

- name: Build StatGen bamUtil 
  community.general.make:
    chdir: "{{bamutil_dir}}"

- name: Create bamUtil module directory
  ansible.builtin.file:
    path: "/apps/modulefiles/bam_util"
    state: directory
    mode: 0775

- name: Create bamUtil LMOD module file
  ansible.builtin.template:
    dest: "/apps/modulefiles/bam_util/1.0.15.lua"
    src: "templates/lmod_module.lua.j2"
